apiVersion: v1
data:
  ANT_VERSION: 1.9.4
  GIT_GLOBAL_CONFIG_EMAIL: jenkins@ldap.example.com
  GIT_GLOBAL_CONFIG_NAME: ADOP Jenkins
  GROOVY_VERSION: 2.4.8
  INITIAL_ADMIN_PASSWORD: admin123
  INITIAL_ADMIN_USER: admin
  JENKINS_OPTS: --prefix=/jenkins
  LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: "false"
  LDAP_DISPLAY_NAME_ATTRIBUTE_NAME: displayName
  LDAP_GROUP_MEMBERSHIP_FILTER: ""
  LDAP_GROUP_NAME_ADMIN: administrators
  LDAP_GROUP_SEARCH_FILTER: ""
  LDAP_INHIBIT_INFER_ROOTDN: "false"
  LDAP_MAIL_ADDRESS_ATTRIBUTE_NAME: mail
  LDAP_MANAGER_DN: cn=admin,dc=ldap,dc=example,dc=com
  LDAP_MANAGER_PASSWORD: admin123
  LDAP_ROOTDN: dc=ldap,dc=example,dc=com
  LDAP_SERVER: ldap
  LDAP_USER_SEARCH: uid={0}
  MAVEN_VERSION: 3.0.5
  NODEJS_GLOBAL_PACKAGES: grunt-cli@~0.1.13 bower@~1.3.12 plato@~1.2.1
  NODEJS_PACKAGES_REFRESH_HOURS: "72"
  NODEJS_VERSION: 6.9.4
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jenkins-jenkins-env
