apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus-rs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus-rs
    spec:
      containers:
      - name: nexus
        image: accenture/adop-nexus:0.1.3
        ports:
        - containerPort: 8081
