apiVersion: v1
kind: Service
metadata:
  labels:
    service: jenkins
  name: jenkins
spec:
  ports:
  - name: "jenkins"
    port: 8080
    targetPort: 8080
  selector:
    app: jenkins-rs
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: jenkins-rs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-rs
    spec:
      containers:
      - name: jenkins
        image: jenkins
        ports:
        - containerPort: 8080
