apiVersion: v1
data:
  GERRIT_PASSWORD: gerrit123
  INITIAL_ADMIN_PASSWORD: admin123
  INITIAL_ADMIN_USER: admin
  JENKINS_PASSWORD: jenkins123
  LDAP_ACCOUNTFULLNAME: ${cn}
  LDAP_ACCOUNTPATTERN: (cn=${username})
  LDAP_ADMIN: admin
  LDAP_DOMAIN: ldap.example.com
  LDAP_FULL_DOMAIN: dc=ldap,dc=example,dc=com
  LDAP_GROUP_BASE_DN: ou=groups
  LDAP_GROUP_NAME_ADMIN: administrators
  LDAP_GROUPMEMBERPATTERN: (uniqueMember=${dn})
  LDAP_GROUPPATTERN: (cn=${groupname})
  LDAP_MANAGER_DN: cn=admin,dc=ldap,dc=example,dc=com
  LDAP_SERVER: ldap:389
  LDAP_USER_BASE_DN: ou=people
  LDAP_USER_SEARCH: uid={0}
  SLAPD_DOMAIN: ldap.example.com
  SLAPD_FULL_DOMAIN: dc=ldap,dc=example,dc=com
  SLAPD_PASSWORD: admin123
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ldap-ldap-env
