apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  ports:
  - name: "ldap"
    port: 389
    targetPort: 389
  selector:
    app: ldap-rs
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: ldap-rs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap-rs
    spec:
      containers:
      - env:
        - name: GERRIT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: GERRIT_PASSWORD
              name: ldap-ldap-env
        - name: INITIAL_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: INITIAL_ADMIN_PASSWORD
              name: ldap-ldap-env
        - name: INITIAL_ADMIN_USER
          valueFrom:
            configMapKeyRef:
              key: INITIAL_ADMIN_USER
              name: ldap-ldap-env
        - name: JENKINS_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: JENKINS_PASSWORD
              name: ldap-ldap-env
        - name: LDAP_ACCOUNTFULLNAME
          valueFrom:
            configMapKeyRef:
              key: LDAP_ACCOUNTFULLNAME
              name: ldap-ldap-env
        - name: LDAP_ACCOUNTPATTERN
          valueFrom:
            configMapKeyRef:
              key: LDAP_ACCOUNTPATTERN
              name: ldap-ldap-env
        - name: LDAP_ADMIN
          valueFrom:
            configMapKeyRef:
              key: LDAP_ADMIN
              name: ldap-ldap-env
        - name: LDAP_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: LDAP_DOMAIN
              name: ldap-ldap-env
        - name: LDAP_FULL_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: LDAP_FULL_DOMAIN
              name: ldap-ldap-env
        - name: LDAP_GROUPMEMBERPATTERN
          valueFrom:
            configMapKeyRef:
              key: LDAP_GROUPMEMBERPATTERN
              name: ldap-ldap-env
        - name: LDAP_GROUPPATTERN
          valueFrom:
            configMapKeyRef:
              key: LDAP_GROUPPATTERN
              name: ldap-ldap-env
        - name: LDAP_GROUP_BASE_DN
          valueFrom:
            configMapKeyRef:
              key: LDAP_GROUP_BASE_DN
              name: ldap-ldap-env
        - name: LDAP_GROUP_NAME_ADMIN
          valueFrom:
            configMapKeyRef:
              key: LDAP_GROUP_NAME_ADMIN
              name: ldap-ldap-env
        - name: LDAP_MANAGER_DN
          valueFrom:
            configMapKeyRef:
              key: LDAP_MANAGER_DN
              name: ldap-ldap-env
        - name: LDAP_SERVER
          valueFrom:
            configMapKeyRef:
              key: LDAP_SERVER
              name: ldap-ldap-env
        - name: LDAP_USER_BASE_DN
          valueFrom:
            configMapKeyRef:
              key: LDAP_USER_BASE_DN
              name: ldap-ldap-env
        - name: LDAP_USER_SEARCH
          valueFrom:
            configMapKeyRef:
              key: LDAP_USER_SEARCH
              name: ldap-ldap-env
        - name: SLAPD_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: SLAPD_DOMAIN
              name: ldap-ldap-env
        - name: SLAPD_FULL_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: SLAPD_FULL_DOMAIN
              name: ldap-ldap-env
        - name: SLAPD_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SLAPD_PASSWORD
              name: ldap-ldap-env
        image: accenture/adop-ldap:0.1.3
        name: ldap-pod
        ports:
        - containerPort: 389
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: ldap-db
      volumes:
      - name: ldap-db
        persistentVolumeClaim:
          claimName: ldap-db

