apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
