apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f jenkins.yml convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: jenkins
status:
  loadBalancer: {}
